schema: schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://quickstart-9ff1ee1f.myshopify.com/api/2024-01/graphql.json
      headers:
        Shopify-Storefront-Private-Token: ${PRIVATE_STOREFRONT_API_TOKEN}
      introspect: false
